# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [3]:
oneD_array = np.array([5,6,7,8])

In [4]:
print(oneD_array)

[5 6 7 8]


In [6]:
twoD_array = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
print(twoD_array)

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
threeD_array = np.array([[[5, 6, 7, 8], [9, 10, 11, 12]], [[1,2, 3, 4], [13, 14, 15, 16]]])

In [9]:
print(threeD_array)

[[[ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [13 14 15 16]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [10]:
twoD_array = np.array([[5, 6, 7, 8], [9, 10, 11, 12]])

In [11]:
 # print number of dimensions
print(twoD_array.ndim)

2


In [12]:
# print row and column number
print(twoD_array.shape) 

(2, 4)


In [13]:
# print number of items in array
print(twoD_array.size)

8


In [14]:
# print data type of the items in array
print(twoD_array.dtype)

int32


In [15]:
# print length of one items in bytes
print(twoD_array.itemsize)

4


In [16]:
# print buffer object pointing to start of array
print(twoD_array.data)

In [17]:
# print size of array in bytes
print(twoD_array.nbytes)

32


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [18]:
# creates an array of 10 one's
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# creates an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# creates an array of dimensions specified, not initialized
np.empty([8, 2])

array([[4.67296746e-307, 1.69121096e-306],
       [8.01093136e-307, 1.11256817e-306],
       [1.06811422e-306, 1.42417221e-306],
       [1.11260619e-306, 8.90094053e-307],
       [1.86919378e-306, 1.06809792e-306],
       [1.37962456e-306, 1.69111861e-306],
       [1.78020169e-306, 1.37961777e-306],
       [7.56599807e-307, 7.56599806e-307]])

In [27]:
# creates an array of dimensions 8 x 2 filled with "2"
np.full((8, 2), 2)

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [28]:
# creates an array of numbers from 1 - 20 using only every 5th
np.arange(1, 20, 5)

array([ 1,  6, 11, 16])

In [29]:
# creates an array starting at 2, ending at 20, filled with 10 numbers
np.linspace(2, 20, 10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [30]:
# creates an array of 10 random numbers between 0 and 1
np.random.random(10)

array([0.33495932, 0.57404721, 0.87261038, 0.82405063, 0.03622936,
       0.3565162 , 0.7708868 , 0.11045809, 0.50981113, 0.52925122])

## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [6]:
# construct arrays
array_e = np.ones((3, 2))
array_f = np.random.random((6, 1, 2))
print(array_e)
print(array_f)

In [10]:
sum = array_e + array_f
print(sum)

[[[1.87617669 1.15390372]
  [1.87617669 1.15390372]
  [1.87617669 1.15390372]]

 [[1.67283089 1.34844636]
  [1.67283089 1.34844636]
  [1.67283089 1.34844636]]

 [[1.86071309 1.45732087]
  [1.86071309 1.45732087]
  [1.86071309 1.45732087]]

 [[1.68121065 1.68866773]
  [1.68121065 1.68866773]
  [1.68121065 1.68866773]]

 [[1.19545912 1.42030642]
  [1.19545912 1.42030642]
  [1.19545912 1.42030642]]

 [[1.10843648 1.45627298]
  [1.10843648 1.45627298]
  [1.10843648 1.45627298]]]


In [12]:
mult = array_e * array_f
print(mult)

[[[0.87617669 0.15390372]
  [0.87617669 0.15390372]
  [0.87617669 0.15390372]]

 [[0.67283089 0.34844636]
  [0.67283089 0.34844636]
  [0.67283089 0.34844636]]

 [[0.86071309 0.45732087]
  [0.86071309 0.45732087]
  [0.86071309 0.45732087]]

 [[0.68121065 0.68866773]
  [0.68121065 0.68866773]
  [0.68121065 0.68866773]]

 [[0.19545912 0.42030642]
  [0.19545912 0.42030642]
  [0.19545912 0.42030642]]

 [[0.10843648 0.45627298]
  [0.10843648 0.45627298]
  [0.10843648 0.45627298]]]


In [13]:
subtr = array_e - array_f
print(subtr)

[[[0.12382331 0.84609628]
  [0.12382331 0.84609628]
  [0.12382331 0.84609628]]

 [[0.32716911 0.65155364]
  [0.32716911 0.65155364]
  [0.32716911 0.65155364]]

 [[0.13928691 0.54267913]
  [0.13928691 0.54267913]
  [0.13928691 0.54267913]]

 [[0.31878935 0.31133227]
  [0.31878935 0.31133227]
  [0.31878935 0.31133227]]

 [[0.80454088 0.57969358]
  [0.80454088 0.57969358]
  [0.80454088 0.57969358]]

 [[0.89156352 0.54372702]
  [0.89156352 0.54372702]
  [0.89156352 0.54372702]]]


In [14]:
array_g = np.ones((5, 8))
array_h = np.random.random((6, 5, 2))

In [15]:
sum = array_g + array_h

ValueError: operands could not be broadcast together with shapes (5,8) (6,5,2) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [19]:
array1 = np.random.random((4, 3)) 
array2 = np.random.random((6, 7, 1))
array3 = np.random.random((2, 4, 2))
print(array1)
print(array2)
print(array3)

[[0.3104655  0.48369523 0.52435171]
 [0.36540895 0.59893747 0.14809683]
 [0.78579995 0.16124105 0.22732655]
 [0.29174218 0.01053346 0.56403835]]
[[[0.32171084]
  [0.27746874]
  [0.14486438]
  [0.81509354]
  [0.77756416]
  [0.60231425]
  [0.08728049]]

 [[0.46837191]
  [0.23087519]
  [0.93106314]
  [0.84861338]
  [0.58564041]
  [0.60629508]
  [0.50742391]]

 [[0.80063262]
  [0.97808722]
  [0.32053921]
  [0.1592595 ]
  [0.7685346 ]
  [0.47486862]
  [0.50231299]]

 [[0.96268032]
  [0.15812362]
  [0.17550434]
  [0.07873943]
  [0.55609128]
  [0.2026025 ]
  [0.91406641]]

 [[0.44657524]
  [0.42124789]
  [0.37205038]
  [0.60954299]
  [0.40452797]
  [0.31410053]
  [0.89355953]]

 [[0.68493714]
  [0.99591154]
  [0.88780991]
  [0.98777977]
  [0.6995028 ]
  [0.34832131]
  [0.53945569]]]
[[[0.95053024 0.81508265]
  [0.72482515 0.73022194]
  [0.16594717 0.5424762 ]
  [0.43534877 0.92289844]]

 [[0.66446564 0.74495081]
  [0.5844892  0.89422084]
  [0.0272754  0.85775599]
  [0.54418874 0.75941424]]]


In [22]:
# sums the array over all elements unless an axis is specified
np.sum(array1)

4.471637238024238

In [24]:
# returns a new array of the smallest element at each position on specified axis
np.minimum(array2, 2)

array([[[0.32171084],
        [0.27746874],
        [0.14486438],
        [0.81509354],
        [0.77756416],
        [0.60231425],
        [0.08728049]],

       [[0.46837191],
        [0.23087519],
        [0.93106314],
        [0.84861338],
        [0.58564041],
        [0.60629508],
        [0.50742391]],

       [[0.80063262],
        [0.97808722],
        [0.32053921],
        [0.1592595 ],
        [0.7685346 ],
        [0.47486862],
        [0.50231299]],

       [[0.96268032],
        [0.15812362],
        [0.17550434],
        [0.07873943],
        [0.55609128],
        [0.2026025 ],
        [0.91406641]],

       [[0.44657524],
        [0.42124789],
        [0.37205038],
        [0.60954299],
        [0.40452797],
        [0.31410053],
        [0.89355953]],

       [[0.68493714],
        [0.99591154],
        [0.88780991],
        [0.98777977],
        [0.6995028 ],
        [0.34832131],
        [0.53945569]]])

In [25]:
# returns a new array of the largest element at each position on specified axis
np.maximum(array3, 3)

array([[[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]]])

In [26]:
# returns cummulative sum of elements along a given axis
np.cumsum(array1, 1)

array([[0.3104655 , 0.79416073, 1.31851244],
       [0.36540895, 0.96434642, 1.11244325],
       [0.78579995, 0.947041  , 1.17436756],
       [0.29174218, 0.30227564, 0.86631399]])

In [27]:
# returns the mean along specified axis
np.mean(array2, 2)

array([[0.32171084, 0.27746874, 0.14486438, 0.81509354, 0.77756416,
        0.60231425, 0.08728049],
       [0.46837191, 0.23087519, 0.93106314, 0.84861338, 0.58564041,
        0.60629508, 0.50742391],
       [0.80063262, 0.97808722, 0.32053921, 0.1592595 , 0.7685346 ,
        0.47486862, 0.50231299],
       [0.96268032, 0.15812362, 0.17550434, 0.07873943, 0.55609128,
        0.2026025 , 0.91406641],
       [0.44657524, 0.42124789, 0.37205038, 0.60954299, 0.40452797,
        0.31410053, 0.89355953],
       [0.68493714, 0.99591154, 0.88780991, 0.98777977, 0.6995028 ,
        0.34832131, 0.53945569]])

In [28]:
# returns Pearson correlation coefficients between two 1D arrays or one 2D array
np.corrcoef(array1)

array([[ 1.        , -0.15850426, -0.96204586,  0.16981626],
       [-0.15850426,  1.        , -0.11694969, -0.99993425],
       [-0.96204586, -0.11694969,  1.        ,  0.1055533 ],
       [ 0.16981626, -0.99993425,  0.1055533 ,  1.        ]])

In [29]:
# returns the standard deviation along specified axis
np.std(array3, 1)

array([[0.29587199, 0.13924655],
       [0.25077192, 0.06343764]])

In [31]:
# returns the variance along specified axis
np.var(array1, axis=0)

array([0.04097254, 0.05635311, 0.03275164])

## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [32]:
# create two boolean arrays of same dimensions
boo1 = [True, False, False, False, True]
boo2 = [True, False, True, True, False]

In [33]:
# apply logical 'and' comparison with boo1 and boo2, returns array of answer
np.logical_and(boo1, boo2)

array([ True, False, False, False, False])

In [40]:
# apply logical 'not' to boo1 returns array of answer
np.logical_not(boo1)

array([False,  True,  True,  True, False])

In [35]:
# apply logical 'or' comparison with boo1 and boo2, returns array of answer
np.logical_or(boo1, boo2)

array([ True, False,  True,  True,  True])